/**
 * Auto-generated migration map for end-user-portal
 * Maps old API function names to generated @autional/shared/generated/api
 * Generated by: python scripts/generate_api_ts.py --migration end-user-portal
 */

import * as Generated from '@autional/shared/generated/api';

export const getSessions = Generated.authMeSessions;
export const revokeSession = Generated.authMeSessionsBySessionsDelete;
export const revokeAllSessions = Generated.authMeSessionsDelete;
export const getMFAStatus = Generated.mfaStatusByStatus;
export const enableTOTP = Generated.mfaTotpEnablePost;
export const verifyTOTP = Generated.mfaTotpVerifyPost;
export const disableTOTP = Generated.mfaTotpDisablePost;
export const getPasskeys = Generated.authMeWebauthnCredentials;
export const deletePasskey = Generated.authMeWebauthnCredentialsByWebauthnCredentialsDelete;
export const getNotifications = Generated.notifications;
export const getUnreadNotifications = Generated.notificationsUnread;
export const markNotificationRead = Generated.notificationsReadByNotificationsPut;
export const markAllNotificationsRead = Generated.notificationsReadAllPut;
export const getWalletBalance = Generated.walletsBalanceByWallets;
export const getPointAccount = Generated.pointsByPoints;
